services:
  web:
    build: .
    command: >
      sh -c "
      python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py populate_es &&
      gunicorn shop.wsgi:application --bind 0.0.0.0:8000
      "
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - media_data:/code/media
      - static_data:/code/static
    depends_on:
      - db
      - es

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-shop}
      POSTGRES_USER: ${POSTGRES_USER:-shop}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-shop}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - es

volumes:
  pg_data:
  es_data:
  media_data:
  static_data:
